# Generated by Django 5.1.15 on 2026-07-13 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0001_initial'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannelMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('channel_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channel_mappings', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'slack_bot_channel_mapping',
                'unique_together': {('team_id', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_user_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slack_bot_user_mapping',
                'unique_together': {('slack_user_id', 'team_id')},
            },
        ),
    ]
