# Generated by Django 5.1.15 on 2026-07-15 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bot', '0002_slack_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('target_slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('performed_by_slack_user_id', models.CharField(default='SYSTEM', max_length=64)),
                ('action', models.CharField(choices=[('ADMIN_BOOTSTRAPPED', 'Admin bootstrapped'), ('ADMIN_UPDATED', 'Admin updated'), ('ACCESS_GRANTED', 'Access granted'), ('BULK_ACCESS_GRANTED', 'Bulk access granted'), ('ACCESS_ALREADY_PRESENT', 'Access already present'), ('ACCESS_RESTORED', 'Access restored'), ('ACCESS_REVOKED', 'Access revoked'), ('INVALID_MEMBER_ID', 'Invalid member ID'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Unauthorized access attempt'), ('ADMIN_NOTIFICATION_SENT', 'Admin notification sent'), ('ADMIN_NOTIFICATION_SUPPRESSED', 'Admin notification suppressed')], db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'slack_bot_access_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slack_bot_administrator',
            },
        ),
        migrations.CreateModel(
            name='BotUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REVOKED', 'Revoked')], db_index=True, default='APPROVED', max_length=16)),
                ('permission', models.CharField(choices=[('READ_ONLY', 'Read-only')], default='READ_ONLY', max_length=16)),
                ('granted_by_slack_user_id', models.CharField(default='SYSTEM', max_length=64)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slack_bot_user_access',
                'unique_together': {('workspace_id', 'slack_user_id')},
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedAccessAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=64)),
                ('slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_admin_notification_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_message_ts', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slack_bot_unauth_access_attempt',
                'unique_together': {('workspace_id', 'slack_user_id')},
            },
        ),
    ]
